version: '3'

services:
  nodeapp:
    build: ./node
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "--timeout", "20s"]
    command: sh -c "npm install && node node.js"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - back-tier

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-tier

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - back-tier
    depends_on:
      - nodeapp

networks:
  back-tier:

volumes:
  db_data:
